name: pokedex_app
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  flutter_riverpod: ^2.4.9
  dio: ^5.4.0
  go_router: ^13.2.0
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0




flutter:
  
  uses-material-design: true
  
  assets:
    - assets/nav_bar/
    - assets/icons/
    - assets/pokemons/
    - assets/pokemons_types/
    - assets/habilities/
    